workflows:
  publish-qa:
    name: Publish QA
    max_build_duration: 60
    environment:
      groups:
        - app_store
        - google_play
        - keystore_credentials
      flutter: 3.7.12
      xcode: 14.3
      cocoapods: default
    cache:
      cache_paths: []
    triggering:
      events:
        # publish only tagged commits to main:
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: false
    scripts:
      - echo $GOOGLE_PLAY_JSON | base64 --decode > google_play.json
      - bundle install
      - bundle exec fastlane setup_keychain
      - |
        # set up release keystore & key.properties
        echo $ANDROID_KEYSTORE | base64 --decode > "$FCI_BUILD_DIR/android/app/itc-release.keystore"
        echo $ANDROID_KEY_PROPERTIES | base64 --decode > "$FCI_BUILD_DIR/android/key.properties"
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - sh ci/build_android_qa.sh
      - find . -name "Podfile" -execdir pod install \;
      - sh ci/build_ios_qa.sh
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - ./*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - ripplearc@gmail.com
  pr:
    name: PR Tests
    max_build_duration: 60
    environment:
      flutter: 3.7.12
      xcode: 14.3
      cocoapods: default
    cache:
      cache_paths: []
    triggering:
      events:
        # test each PR to main:
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: false
    scripts:
      - bundle install
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - bundle exec fastlane test
    publishing:
      email:
        recipients:
          - ripplearc@gmail.com